Implemented claw class and changed the end effector interface
R2D2-2019/end_effectors pull request #2
Opened 2019-05-29 17:12 UTC by denizlektemur

The claw class has been implemented to work with the end effector interface.
The end effector interface has been changed slightly by moving the enum to internal comm and adding some functions so that the interface works with the can bus.

2019-06-18 14:45 UTC, LRstudentHU requested changes

2019-06-18 14:45 UTC, LRstudentHU commented on code/headers/claw.hpp
> +        claw_c(hwlib::target::pin_adc pot_pin = hwlib::target::pin_adc(hwlib::target::ad_pins::a0),
I believe there is an interface available for the adc (e.g. hwlib::adc). Maybe you could receive that by reference? That way, you can write tests.

2019-06-18 14:45 UTC, LRstudentHU commented on code/main.cpp
> +    auto end_effector = r2d2::end_effectors::claw_c();
I don't understand why you create the pointer like this. On line 20, you could do `&end_effector` to pass it as a pointer.

2019-06-18 14:45 UTC, LRstudentHU commented on code/src/claw.cpp
> +            hwlib::wait_ms(1);
Do you need to wait this long? Note that this will not do what you expect in an RTOS environment.

2019-06-18 14:45 UTC, LRstudentHU commented on test/Makefile
> -SOURCES := $(wildcard ../code/src/*.cpp)
Is this intentional?

2019-06-18 15:05 UTC, denizlektemur commented on test/Makefile
> -SOURCES := $(wildcard ../code/src/*.cpp)
Yes if I use the wildcard lines travis gives an error about including the pwm library

2019-06-18 15:06 UTC, denizlektemur commented on code/src/claw.cpp
> +            hwlib::wait_ms(1);
The potmeter inside the servo needs some time to change its value. If I dont use a wait the reading will be inaccurate.

2019-06-18 15:12 UTC, denizlektemur commented on code/main.cpp
> +    auto end_effector = r2d2::end_effectors::claw_c();
Good point I have changed it

2019-06-18 16:33 UTC, LRstudentHU requested changes

2019-06-18 16:33 UTC, LRstudentHU commented on code/src/claw.cpp
> +            hwlib::wait_ms(1);
Yes, but do you need to wait for 1ms? Would 100msec give an inaccurate result? The module scheduler (HU-RTOS) will allow other tasks to run during this; if that shouldn't happen please use the busy wait

2019-06-18 16:33 UTC, LRstudentHU commented on test/Makefile
> -SOURCES := $(wildcard ../code/src/*.cpp)
Do you have a main file for tests?

2019-06-18 16:42 UTC, denizlektemur commented on code/src/claw.cpp
> +            hwlib::wait_ms(1);
When testing it approximately needed 1ms to be consistent. I changed the wait to a busy wait.

2019-06-18 16:43 UTC, denizlektemur commented on test/Makefile
> -SOURCES := $(wildcard ../code/src/*.cpp)
I do have a main for tests but I havent changed anything in that main. It still has the standard code in it.

2019-06-24 22:13 UTC, denizlektemur commented on code/headers/claw.hpp
> +        claw_c(hwlib::target::pin_adc pot_pin = hwlib::target::pin_adc(hwlib::target::ad_pins::a0),
If I try it that way I get the error parameter of abstract class type hwlib::adc is not allowed.

2019-06-25 12:10 UTC, LRstudentHU commented on code/headers/claw.hpp
> +        claw_c(hwlib::target::pin_adc pot_pin = hwlib::target::pin_adc(hwlib::target::ad_pins::a0),
`hwlib::adc` is an abstract class; that means you'll have to receive it by reference in the constructor. When instantiating your module, you'll pass the `hwlib::target::pin_adc` as normal.

2019-06-25 12:33 UTC, LRstudentHU approved these changes

2019-06-25 12:33 UTC, merged