First release to master
R2D2-2019/end_effectors pull request #3
Opened 2019-06-25 12:35 UTC by denizlektemur

Features
- Opening and closing of the claw
- Claw stops closing when an object is between the claw
- Works with the internal communication frames

2019-06-25 13:23 UTC, itzandroidtab requested changes

2019-06-25 13:23 UTC, itzandroidtab commented on test/main.cpp
> +#include "ostream"
Can you change the `""` to `<>`?

2019-06-25 13:23 UTC, itzandroidtab commented on code/headers/module.hpp
> +        module_c(base_comm_c &comm, end_effector_c *end_effector);
Why is the `enc_effector_c` parameter a pointer? If you do it by reference there is no need for `nullptr` checks.

2019-06-25 13:23 UTC, itzandroidtab commented on code/src/module.cpp
> +            if(end_effector != nullptr){
Why does the constructor need to care if we have a `nullptr`? The module should alway's have a `end_effector` otherwise this module is useless. See previous comment.

2019-06-25 13:23 UTC, itzandroidtab commented on code/src/module.cpp
> +        if(end_effector != nullptr){
Same as other one.

2019-06-25 13:23 UTC, itzandroidtab commented on code/headers/claw.hpp
> +        r2d2::pwm_lib::pwm_c pwm;
Dont you want a reference to the pwm pin instead of making a copy?

2019-06-25 13:23 UTC, itzandroidtab commented on code/headers/claw.hpp
> +        int32_t calc_pot_difference(uint8_t current_pwm);
What is the range the pot works in? The range of the adc is 10 or 12 bits. So I am not sure if we need a int32_t for this.

2019-06-25 13:23 UTC, itzandroidtab commented on code/headers/claw.hpp
> +         * @param pot_pin A hwlib adc pin to read the potmeter inside the servo of the claw
These lines are a bit on the long side. Can you format them?

2019-06-25 13:23 UTC, itzandroidtab commented on code/src/claw.cpp
> +                if(difference > 100 || difference < -100) {
What does -100 and 100 do? Can you explain where the numbers come from?

2019-06-25 13:23 UTC, itzandroidtab commented on code/src/claw.cpp
> +        hwlib::wait_ms(1000);
What is the reason you are waiting here? And why 1000 ms?

2019-06-25 13:23 UTC, itzandroidtab commented on code/src/claw.cpp
> +                hwlib::wait_ms(80);
And here as well.

2019-06-25 13:23 UTC, itzandroidtab commented on code/src/claw.cpp
> +        for(uint8_t i = 0; i < pot_scans; i++) {
Could you add a comment that you are waiting for 50 ms here? And a warning to the doxygen as this is a busy wait? And do you mind explaining why you need a busy wait here?

2019-06-25 13:23 UTC, itzandroidtab commented on code/src/claw.cpp
> +        pot_value = 0;
Can you change the:

```cpp
uint32_t pot_value;
```

to 

```cpp
uint32_t pot_value = 0;
```

and remove this line?

2019-06-25 13:23 UTC, itzandroidtab commented on code/src/claw.cpp
> +        expected_pot = pot_per_pwm_step * (current_pwm-open_pwm) + pot_offset;
Can you change this to:

```cpp
uint32_t expected_pot = pot_per_pwm_step * (current_pwm-open_pwm) + pot_offset;
```

?

2019-06-25 13:23 UTC, itzandroidtab commented on code/main.cpp
> +#include "hwlib.hpp"
Can you change the include to `<>`?

2019-06-25 13:23 UTC, itzandroidtab commented
Some of the lines are a bit on the long side. Can you format the files just to be sure?

2019-06-27 12:08 UTC, denizlektemur commented on code/src/claw.cpp
> +                if(difference > 100 || difference < -100) {
These are the values used to determine if there is collision. If the current pot value has a offset of more than 100 with the expected pot the claw will stop closing. We used 100 and -100 because the average differences (that should still be acceptable) is around 50 and -50. So we used 100 and -100 as the threshold values in case of unexpected peaks.

2019-06-27 12:11 UTC, denizlektemur commented on code/src/claw.cpp
> +        hwlib::wait_ms(1000);
Opening the claw can take some time if the claw is already closed. The potmeter also takes some time to update to the new position of the claw. So to get accurate readings from the potmeter we wait 1000 ms for the potmeter to adjust to the sudden movement of the claw in case the claw is closed when starting this function. The reason we use 1000ms is because this value never seemed to give any problems while some lower values did.

2019-06-27 12:14 UTC, denizlektemur commented on code/src/claw.cpp
> +                hwlib::wait_ms(80);
Closing the claw 1 step can take some time. The potmeter also takes some time to update to the new position of the claw. So to get accurate readings from the potmeter we wait 80 ms for the potmeter to adjust to the movement of the claw. The reason we use 80 ms is because this value never seemed to give any problems while some lower values did.

2019-06-27 12:21 UTC, denizlektemur commented on code/src/claw.cpp
> +        for(uint8_t i = 0; i < pot_scans; i++) {
We use a busy wait because we use 50 waits of 1 ms. If this task switched everytime it waits for 1 ms it would make the resulting wait way longer than 50 ms. This would result in a very long wait just to calculate a pot difference and would make closing the claw way slower.

2019-06-27 12:51 UTC, denizlektemur commented on test/main.cpp
> +#include "ostream"
https://github.com/R2D2-2019/end_effectors/commit/8866d672160e34b23dcb0d9f1029ae4ed4ed2570

2019-06-27 12:51 UTC, denizlektemur commented on code/headers/module.hpp
> +        module_c(base_comm_c &comm, end_effector_c *end_effector);
https://github.com/R2D2-2019/end_effectors/commit/6adee8f175e80fdd399b6c3f3a1e5240a579763c

2019-06-27 12:52 UTC, denizlektemur commented on code/src/module.cpp
> +            if(end_effector != nullptr){
https://github.com/R2D2-2019/end_effectors/commit/6adee8f175e80fdd399b6c3f3a1e5240a579763c

2019-06-27 12:52 UTC, denizlektemur commented on code/src/module.cpp
> +        if(end_effector != nullptr){
https://github.com/R2D2-2019/end_effectors/commit/6adee8f175e80fdd399b6c3f3a1e5240a579763c

2019-06-27 12:52 UTC, denizlektemur commented on code/headers/claw.hpp
> +        r2d2::pwm_lib::pwm_c pwm;
https://github.com/R2D2-2019/end_effectors/commit/8cadbf6bf86f8acc1be27a9fb9e6983c697f2dd8

2019-06-27 12:52 UTC, denizlektemur commented on code/headers/claw.hpp
> +        int32_t calc_pot_difference(uint8_t current_pwm);
https://github.com/R2D2-2019/end_effectors/commit/d7049e7f61a9ccb34978509b510726954a61c581

2019-06-27 12:53 UTC, denizlektemur commented on code/headers/claw.hpp
> +         * @param pot_pin A hwlib adc pin to read the potmeter inside the servo of the claw
https://github.com/R2D2-2019/end_effectors/commit/b7913252ec9bc0a13db00edbb48cdb89d6020a00

2019-06-27 12:53 UTC, denizlektemur commented on code/src/claw.cpp
> +        for(uint8_t i = 0; i < pot_scans; i++) {
https://github.com/R2D2-2019/end_effectors/commit/6f7c83491f9f588017f1396176584145bfeac4fb

2019-06-27 12:53 UTC, denizlektemur commented on code/src/claw.cpp
> +        pot_value = 0;
https://github.com/R2D2-2019/end_effectors/commit/4866d66f7cebbf5d32b2cdc8c0478ce0fbfe89be

2019-06-27 12:53 UTC, denizlektemur commented on code/src/claw.cpp
> +        expected_pot = pot_per_pwm_step * (current_pwm-open_pwm) + pot_offset;
https://github.com/R2D2-2019/end_effectors/commit/4866d66f7cebbf5d32b2cdc8c0478ce0fbfe89be

2019-06-27 12:53 UTC, denizlektemur commented on code/main.cpp
> +#include "hwlib.hpp"
https://github.com/R2D2-2019/end_effectors/commit/8866d672160e34b23dcb0d9f1029ae4ed4ed2570

2019-06-27 13:04 UTC, itzandroidtab commented on code/headers/claw.hpp
> +         r2d2::pwm_lib::pwm_c &pwm_pin);
Is this too long for a single line?

2019-06-27 13:05 UTC, itzandroidtab commented on code/headers/claw.hpp
> +         * This function waits for 50 ms
Can you change this to a 

```cpp
 * @warning This function waits for 50 ms 
 * The wait we use is a busy wait this means
 * that we cant switch tasks during this wait
```

So doxygen will give a nice warning message.

2019-06-27 13:09 UTC, itzandroidtab commented on code/src/claw.cpp
> +                if(difference > 100 || difference < -100) {
This is pretty important then.

Can you change the 100 and -100 to something like:

```cpp
constexpr static uint8_t grip_threshold = 100;

if(difference > grip_threshold || difference < (-1 * grip_threshold)) {
```

2019-06-28 11:08 UTC, denizlektemur commented on code/headers/claw.hpp
> +         * This function waits for 50 ms
https://github.com/R2D2-2019/end_effectors/commit/dabab7c4fc3200cfaefa5fb294790c2e7e2d541d

2019-06-28 11:09 UTC, denizlektemur commented on code/headers/claw.hpp
> +         r2d2::pwm_lib::pwm_c &pwm_pin);
https://github.com/R2D2-2019/end_effectors/commit/a0b6c8198bbda6ddc2771fd711944693e5fc5534

2019-06-28 11:09 UTC, denizlektemur commented on code/src/claw.cpp
> +                if(difference > 100 || difference < -100) {
https://github.com/R2D2-2019/end_effectors/commit/c5f319d16370cde1df8a1b6f6692c02205b8f918

2019-06-28 13:00 UTC, itzandroidtab approved these changes

2019-06-29 14:24 UTC, gerritvanos requested changes
only one small change otherwise code looks good to me

2019-06-29 14:24 UTC, gerritvanos commented on code/src/claw.cpp
> +        int16_t difference;
I believe this variable is not necessary since the calculation can be returned immediately without the need of first setting the variable on line 22/23

2019-06-29 14:33 UTC, gerritvanos commented
could you format the files aswell some places look unformatted

2019-06-30 10:42 UTC, denizlektemur commented on code/src/claw.cpp
> +        int16_t difference;
I changed it https://github.com/R2D2-2019/end_effectors/commit/08b8a8de3bf3d405ee43d5131ed488db4a2fb4f7
I also formatted the files https://github.com/R2D2-2019/end_effectors/commit/8d72b11f3acb8f2f352158eca13de4cccf04e9c1

2019-06-30 11:18 UTC, gerritvanos approved these changes
looks good now

2019-06-30 11:19 UTC, merged